log_path: /home/yxt/code/slam/intensity_calib_fred_ws/src/intensity_calibration/log/
result_path: /home/yxt/code/slam/intensity_calib_fred_ws/src/intensity_calibration/results/
# poincloud
# pcd_path: /home/yxt/code/slam/intensity_calib_fred_ws/src/intensity_calibration/sample/test_uniform_0.1.pcd
pcd_path: /home/yxt/code/slam/kumo_slam_ws/src/kumo_slam/results/full_cloud.pcd
voxel_size: 0.3
max_distance: 30
# 
std_var: 0.5
eps: 0.05
max_intensity: 100
value_converge: 1e-6
save_loss_value: false
#
max_em_epoch: 100
use_original_em: true
original_em_precision: 1e-10